mysql:
#  host: XXX.sql.tencentcdb.com
  host: XXX
#  port: 63939
  port: 3306
  user: root
  password: XXX
  dbname: test

redis:
  addr: XXX:6379
  password: XXX
  db: 0

log:
  filePath: "/tmp/gin.log"
